[build]
  # Build from repo root; install root deps for Functions
  command = "npm --prefix client ci && npm --prefix client run build"
  publish = "client/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  # CRA treats warnings as errors when CI=true; disable to allow warnings
  CI = "false"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Ensure SPA routes serve index.html
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/company/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/review/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/events"
  to = "/index.html"
  status = 200
