export const items = {
  a: {
    id: "a",
    name: "Plumbing",
    latinName: "Persea americana",
    description:
      "An oddly creamy fruit. Surprisingly high in protein. Has a big pit in the middle.  You're not supposed to eat the rind. Millenials like to put it on toast, for reasons not entirely understood.",
    imageSrc: "/assets/plumbing.jpg",
    countryOfOrigin: "Mexico",
    sellerId: "alice",
    price: 8,
    quantity: 2,
  },
  b: {
    id: "b",
    name: "Home repair",
    latinName: "Musa acuminata",
    description: "A mushy, mealy fruit 🤢",
    imageSrc: "/assets/HomeRepair.jpg",
    countryOfOrigin: "Ecuador",
    sellerId: "bob",
    price: 5,
    quantity: 500,
  },
  c: {
    id: "c",
    name: "Auto Repair",
    latinName: "Prunus avium",
    description: "You're a big winner if you get 3 of these on a slot machine!",
    imageSrc: "/assets/AutoRepair.jpg",
    countryOfOrigin: "Turkey",
    sellerId: "bob",
    price: 3.49,
    quantity: 0,
  },
  d: {
    id: "d",
    name: "Auto Dealers",
    latinName: "Citrus aurantiifolia",
    description: "The most underrated citrus.",
    imageSrc: "/assets/AutoDealers.jpg",
    countryOfOrigin: "Spain",
    sellerId: "alice",
    price: 0.99,
    quantity: 5,
  },
  e: {
    id: "e",
    name: "Insurance",
    latinName: "Citrus × sinensis",
    description: "Frequently turned into juice.",
    imageSrc: "/assets/Insurance.jpg",
    countryOfOrigin: "United States",
    sellerId: "alice",
    price: 1.49,
    quantity: 28,
  },
  f: {
    id: "f",
    name: "Fitness",
    latinName: "Citrus limon caeruleum",
    description:
      "Fantastical, mythological item. Exists only in other universes",
    imageSrc: "/assets/Fitness.jpg",
    countryOfOrigin: "Valhalla",
    sellerId: "bob",
    price: 400,
    quantity: 0,
  },
  g: {
    id: "g",
    name: "Beauty salons",
    latinName: "Citrus limon caeruleum",
    description:
      "Fantastical, mythological item. Exists only in other universes",
    imageSrc: "/assets/BeautySalon.jpg",
    countryOfOrigin: "Valhalla",
    sellerId: "bob",
    price: 400,
    quantity: 0,
  },
  h: {
    id: "h",
    name: "Banks",
    latinName: "Citrus limon caeruleum",
    description:
      "Fantastical, mythological item. Exists only in other universes",
    imageSrc: "/assets/Banks.jpg",
    countryOfOrigin: "Valhalla",
    sellerId: "bob",
    price: 400,
    quantity: 0,
  },
  i: {
    id: "i",
    name: "Tourism",
    latinName: "Citrus limon caeruleum",
    description:
      "Fantastical, mythological item. Exists only in other universes",
    imageSrc: "/assets/Tourism.jpg",
    countryOfOrigin: "Valhalla",
    sellerId: "bob",
    price: 400,
    quantity: 0,
  },
  j: {
    id: "j",
    name: "Restaurants",
    latinName: "Citrus limon caeruleum",
    description:
      "Fantastical, mythological item. Exists only in other universes",
    imageSrc: "/assets/Restaurant.jpg",
    countryOfOrigin: "Valhalla",
    sellerId: "bob",
    price: 400,
    quantity: 0,
  },
  k: {
    id: "k",
    name: "Fitness Training",
    latinName: "Citrus limon caeruleum",
    description:
      "Fantastical, mythological item. Exists only in other universes",
    imageSrc: "/assets/Fitness.jpg",
    countryOfOrigin: "Valhalla",
    sellerId: "bob",
    price: 400,
    quantity: 0,
  },
};
